[build]
  command = "npm run build"
  publish = "build"   # or "dist" if you're using Vite

# Redirect all routes to index.html (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200